import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';
import { Transaction,TransactionPDFProps } from '@/app/types/appTypes';

// Create styles
const baseTableCell = {
  margin: 'auto',
  marginTop: 5,
  fontSize: 10,
  padding: 5,
};

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 30,
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1,
  },
  title: {
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 20,
    fontWeight: 'bold',
    color: '#2563eb',
  },
  table: {
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderColor: '#e5e7eb',
  },
  tableRow: {
    margin: 'auto',
    flexDirection: 'row',
  },
  tableCol: {
    width: '20%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderColor: '#e5e7eb',
  },
  tableCell: baseTableCell,
  tableCellHeader: {
    ...baseTableCell,
    fontWeight: 'bold',
  },
  expenseCell: {
    ...baseTableCell,
    color: '#dc2626',
  },
  incomeCell: {
    ...baseTableCell,
    color: '#16a34a',
  },
});


// PDF Document Component


const tableHeaders = ['Date', 'Description', 'Category', 'Amount', 'Type'];

const renderTransactionRow = (transaction: Transaction, index: number, currency: string) => (
  <View style={styles.tableRow} key={index}>
    <View style={styles.tableCol}>
      <Text style={styles.tableCell}>
        {transaction.date
          ? new Date(transaction.date as string | number | Date).toLocaleDateString("en-GB")
          : ""}
      </Text>
    </View>
    <View style={styles.tableCol}>
      <Text style={styles.tableCell}>{transaction.description}</Text>
    </View>
    <View style={styles.tableCol}>
      <Text style={styles.tableCell}>{String(transaction.category || '')}</Text>
    </View>
    <View style={styles.tableCol}>
      <Text style={styles.tableCell}>
        {transaction.amount} {currency}
      </Text>
    </View>
    <View style={styles.tableCol}>
      <Text style={transaction.type === 'Expense' ? styles.expenseCell : styles.incomeCell}>
        {transaction.type}
      </Text>
    </View>
  </View>
);

const TransactionPDF: React.FC<TransactionPDFProps> = ({
  transactions = [],
  selectedCategory = "All",
  currency = "INR",
  categories = []
}) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <Text style={styles.title}>Transaction Report</Text>
        <Text style={{ fontSize: 12, marginBottom: 10, textAlign: 'center' }}>
          {selectedCategory === "All" ? `Categories: All (${categories.join(', ')})` : `Category: ${selectedCategory}`}
        </Text>
        <View style={styles.table}>
          {/* Table Header */}
          <View style={styles.tableRow}>
            {tableHeaders.map((header, index) => (
              <View key={index} style={styles.tableCol}>
                <Text style={styles.tableCellHeader}>{header}</Text>
              </View>
            ))}
          </View>
          {/* Table Body */}
          {transactions.length > 0 ? transactions.map((transaction, index) => renderTransactionRow(transaction, index, currency)) : (
            <View style={styles.tableRow}>
              <View style={{...styles.tableCol, width: '100%'}}>
                <Text style={{...styles.tableCell, textAlign: 'center'}}>No transactions found</Text>
              </View>
            </View>
          )}
        </View>
        <Footer />
      </View>
    </Page>
  </Document>
);

const Footer: React.FC = () => (
  <>
    <Text style={{ fontSize: 8, textAlign: 'center', marginTop: 20, color: '#6b7280' }}>
      Generated by BudgetBuddy App - Your Personal Finance Companion
    </Text>
    <Text style={{ fontSize: 6, textAlign: 'center', marginTop: 5, color: '#9ca3af' }}>
      Generated on {new Date().toLocaleDateString()}
    </Text>
  </>
);

export { TransactionPDF };